variables:
  NODE_VERSION: 20
  JAVA_VERSION: 21
  DEBIAN_FRONTEND: "noninteractive"

image: ubuntu:22.04

# 1. Split the build stage to enforce sequential ordering
stages:
  - build-server
  - build-client
  - test

.setup_env: &setup_env
  before_script:
    - apt-get update -qq
    - apt-get install -y -qq curl ca-certificates gnupg xvfb
    - curl -fsSL https://deb.nodesource.com/setup_$NODE_VERSION.x | bash -
    - apt-get install -y -qq nodejs openjdk-$JAVA_VERSION-jdk maven
    - npm install -g yarn lerna

build_server:
  stage: build-server
  <<: *setup_env
  script:
    - cd server
    - mvn --batch-mode clean verify
  artifacts:
    paths:
      - "server/**/target/uvl.glsp-*-glsp.jar"
    expire_in: 1 hour

build_client:
  stage: build-client
  <<: *setup_env
  script:
    - cd client
    - yarn cache clean
    - yarn
    - yarn package
  needs:
    - build_server
  artifacts:
    paths:
      - "client/**/**/*.vsix"
    expire_in: 1 hour

run_playwright_tests:
  stage: test
  <<: *setup_env
  script:
    - cd test
    - yarn cache clean
    - yarn
    - yarn test
  needs:
    - build_server
    - build_client
  artifacts:
    when: always
    paths:
      - "test/playwright-report/"
      - "test/test-results/"
    expire_in: 7 days